- src/main/java/com/seveneleven/devlens/global/util/file/entity/FileMetadata.java
- src/main/java/com/seveneleven/devlens/global/util/file/entity/FileMetadataHistory.java
closes #9
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Fix: File Entity Exception 수정

- .github/workflows/build_test.yml
- build.gradle
- src/main/resources/application.properties
<br />
- 테스트 자동화 워크 플로우 추가
<br />
ex) 
1. 민감하지 않은 정보 환경변수 해제 : 포트, 배너, 타입 설정, JPA 설정
2. 태스트 워크플로우 생성
<br />
ex)
1. ./gradlew claen test
<br />
closes : #12
> [CI] : 테스트 자동화 플로우 추가

- .github/CODEOWNERS
- .github/auto_assign.yml
- .github/workflows/auto_assign.yml
<br />
ex) 
pr시 코드 리뷰어 자동 등록 플로우 추가
<br />
ex) 
1. pr시 코드 리뷰어 자동 등록 플로우 추가
<br />
ex)
1. pr 해봐야함
> Setting : pr 시 코드 리뷰어 자동 등록

- .github/workflows/ai_code_reviewer.yml
- 코드리뷰 수준이 만족스럽지 않음
- 사용 해보고 효율성이 없다고 판단되면 제거 예정
closes : #21
<br />
1. pr시에 ai 코드리뷰
<br />
1. pr시에 ai 코드리뷰
<br />
1. pr 올려봐야 함
> Setting : Ai 코드리뷰 플로우 추가

- src/main/java/com/seveneleven/devlens/domain/board/entity/Comment.java
- src/main/java/com/seveneleven/devlens/domain/board/entity/Post.java
- src/main/java/com/seveneleven/devlens/domain/board/entity/PostHistory.java
- src/main/java/com/seveneleven/devlens/domain/board/entity/Question.java
- src/main/java/com/seveneleven/devlens/domain/member/constant/BusinessType.java
- src/main/java/com/seveneleven/devlens/domain/member/constant/MemberStatus.java
- src/main/java/com/seveneleven/devlens/domain/member/constant/Role.java
- src/main/java/com/seveneleven/devlens/domain/member/constant/TermsStatus.java
- src/main/java/com/seveneleven/devlens/domain/member/constant/YN.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/Company.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/Department.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/Member.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/MemberPasswordResetHistory.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/MemberProfileHistory.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/Position.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/Term.java
- src/main/java/com/seveneleven/devlens/domain/member/entity/TermsAgreementHistory.java
- src/main/java/com/seveneleven/devlens/domain/project/entity/CheckRequest.java
- src/main/java/com/seveneleven/devlens/domain/project/entity/CheckResult.java
- src/main/java/com/seveneleven/devlens/domain/project/entity/Project.java
- src/main/java/com/seveneleven/devlens/domain/project/entity/ProjectAuthorization.java
- 회원 관련 Entity 어노테이션 수정
- 상태, YN Enum 타입 추가
- id 컬럼명, 변수명 수정
close: #28 
<br />
회원 관련 Entity 수정
<br />
1. 회원, 회원 이력, 약관, 회사, 부서, 직책 엔티티티 수정
2. Entity 어노테이션 수정
3. enum 타입 추가
4. 테이블 pk 컬럼명 'id'로 수정
5. fk에서 id 못 찾는 오류가 발생 -> JoinColumn에 **referencedColumnName = "id"** 옵션 추가
<br />
> Feat: 회원 Entity 수정

- src/main/java/com/seveneleven/devlens/global/config/AuditorAwareImpl.java
- src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
- src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
- src/main/java/com/seveneleven/devlens/global/util/file/Service/S3ClientService.java
- src/main/java/com/seveneleven/devlens/global/util/file/controller/FileController.java
- src/main/java/com/seveneleven/devlens/global/util/file/dto/FileMetadataDto.java
- src/test/java/com/seveneleven/devlens/global/util/file/Service/FileServiceTest.java
<br />
수정된 Entity를 적용하여 파일 업로드 베이스 코드 수정
<br />
1. FileService, S3ClientService 수정
2. FileMetadataDto 수정
3. FileController 수정
4. 연관 ErrorCode 수정
5. FileService Test코드 작성
<br />
1. FileService Test수행
2. Postman을 활용한 통합테스트
<br />
<br />
Service의 기능 분리는 리팩토링시 분리하겠습니다.
> Update: 파일 업로드 베이스 코드 수정

- src/main/java/com/seveneleven/devlens/global/entity/BaseEntity.java
<br />
Base Entity 생성자, 수정자 타입 변경
<br />
baseEntity 수정 - createdBy, updatedBy 타입 String -> Long 수정
<br />
MySQL - 컬럼 타입 BIGINT 확인
<br />
<br />
> Update: Base Entity 생성자, 수정자 타입 변경

- src/main/java/com/seveneleven/devlens/domain/admin/controller/CompanyController.java
<br />
ResponseEntity로 반환값 수정
<br />
> Update : 회사 ResponseEntity 적용

- src/main/java/com/seveneleven/devlens/domain/project/controller/MyProjectController.java
- src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectChecklistController.java
- src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectController.java
- (T data)를 사용하던 것에서 (SuccessCode, T data)를 사용하도록 변경
<br />
ex) 
<br />
- APIResponse(T data)를 사용하던 것을 APIResponse(SuccessCode, T data)를 사용하도록 변경
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> fix : api response 변경

- src/main/java/com/seveneleven/devlens/domain/admin/controller/CompanyController.java
> Feature : 응답 body 수정

- src/main/java/com/seveneleven/devlens/global/response/APIResponse.java
- src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
<br />
- APIResponse 미사용 메서드 제외
- #50 
<br />
<br />
<br />
<br />
> feature/apiresponse-update #50

- .github/workflows/build_test.yml
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> CI : 깃허브 액션 멀티모듈 브랜치 추가

- Common/src/main/java/com/seveneleven/config/JwtAuthenticationEntryPoint.java
- Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
- Common/src/main/java/com/seveneleven/config/SwaggerConfiguration.java
<br />
Swagger 토큰 api 추가
<br />
Swagger 토큰 api 추가
<br />
스웨거
<br />
> Feat: add swagger config

- Admin/src/main/java/com/seveneleven/controller/CompanyFileController.java
- Admin/src/main/java/com/seveneleven/service/CompanyFileService.java
- Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
- Common/src/main/java/com/seveneleven/response/ErrorCode.java
- Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
- Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
<br />
회원 프로필 이미지 등록/삭제/조회 구현
<br />
1. MyPageController 프로필 이미지 등록/삭제/조회 메서드 추가
2. MemberFileService 추가
3. 관련 ErrorCode 추가
4. SpringSecurityConfig 수정
<br />
1. postman 요청
2. S3 버킷 확인
3. MySQL 확인
<br />
> FEATURE/ 회원 프로필 이미지 등록/삭제/조회

- Admin/src/main/resources/application.properties
- Common/src/main/resources/application.properties
- Main/src/main/java/com/seveneleven/member/controller/MemberController.java
- Main/src/main/java/com/seveneleven/member/controller/MemberDocs.java
- Main/src/main/java/com/seveneleven/member/dto/LoginPost.java
- Main/src/main/java/com/seveneleven/member/dto/LoginResponse.java
- Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
- Main/src/main/resources/application.properties
close: #98 
<br />
로그인 페이지 API 응답 데이터 추가 및 수정
<br />
1. 로그인 응답 데이터 추가
2. request  json key 검증 에러 설정(배포 시, 제거할 예정)
3. 비밀번호 재설정 코드 수정
<br />
스웨거 및 postman 테스트
<br />
> Feature/member login fix #98

- Common/src/main/java/com/seveneleven/entity/project/CheckResult.java
- Common/src/main/java/com/seveneleven/entity/project/ChecklistHistory.java
- Common/src/main/java/com/seveneleven/entity/project/ProjectStep.java
- Common/src/main/java/com/seveneleven/response/ErrorCode.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectStepController.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectStepDocs.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectStepFacade.java
- Main/src/main/java/com/seveneleven/project/dto/DeleteProjectStep.java
- Main/src/main/java/com/seveneleven/project/dto/PutProjectStep.java
- Main/src/main/java/com/seveneleven/project/repository/ChecklistRepository.java
- Main/src/main/java/com/seveneleven/project/service/ProjectStepServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestReaderImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStore.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStoreImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistReader.java
- Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistReaderImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistStore.java
- Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistStoreImpl.java
- Main/src/main/java/com/seveneleven/project/service/step/StepReader.java
- Main/src/main/java/com/seveneleven/project/service/step/StepReaderImpl.java
- Main/src/main/java/com/seveneleven/project/service/step/StepStore.java
- Main/src/main/java/com/seveneleven/project/service/step/StepStoreImpl.java
<br />
- 프로젝트 단계 수정
- 프로젝트 단계 삭제
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Feature : step api #78

- Admin/src/main/java/com/seveneleven/service/CompanyFileService.java
- Common/src/main/java/com/seveneleven/config/CustomUserDetailsService.java
- Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
- Common/src/main/java/com/seveneleven/response/ErrorCode.java
- Common/src/main/java/com/seveneleven/util/file/Service/FileService.java
- Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataRepository.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
- Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
<br />
게시물 관련 파일 기능 구현(코어)
<br />
1. FileService 수정
2. FileMetadataRepository 수정
3. PostRepository 수정
4. PostFileService 추가
5. PostService, PostServiceImpl 수정
6. 관련 ErrorCode 수정
7. BoardController 수정
<br />
1. Swagger 작동 확인
2. MySQL 확인
3. S3 버킷 확인
<br />
> FEATURE: 게시물 관련 파일 기능 추가

- Common/src/main/java/com/seveneleven/entity/board/Comment.java
- Common/src/main/java/com/seveneleven/response/ErrorCode.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/controller/CommentController.java
- Main/src/main/java/com/seveneleven/board/controller/CommentDocs.java
- Main/src/main/java/com/seveneleven/board/dto/DeleteCommentRequest.java
- Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
- Main/src/main/java/com/seveneleven/board/dto/PatchCommentRequest.java
- Main/src/main/java/com/seveneleven/board/dto/PostCommentRequest.java
- Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
- Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
- Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
- Main/src/main/java/com/seveneleven/board/service/CommentService.java
- Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
댓글 조회, 생성, 수정, 삭제 기능 구현
<br />
1. 댓글 조회, 생성, 수정, 삭제 기능 구현
<br />
1. 스웨거
> Feat: 댓글 기능 구현 #97

- Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
close: #123 
<br />
jwt filter 임시 해제
<br />
jwt 관련 코드 주석 처리
<br />
> Feat: jwt filter 해제

- Admin/src/main/resources/application.properties
- Common/src/main/java/com/seveneleven/util/file/FileValidator.java
- Common/src/main/java/com/seveneleven/util/file/Service/FileService.java
- Common/src/main/java/com/seveneleven/util/file/Service/LinkService.java
- Common/src/main/java/com/seveneleven/util/file/Service/S3ClientService.java
- Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataRepository.java
- Common/src/main/resources/application.properties
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/resources/application.properties
<br />
게시물 파일 업로드 분리
<br />
1. 게시물 파일 업로드 controller, service 분리
2. multipart 사이즈 관련 application.properties 수정
<br />
1. postman, swagger 작동확인
2. S3 버킷확인
3. MySQL 확인
<br />
<br />
> update: 게시물 파일 업로드 분리

- Admin/build.gradle
- Admin/src/main/resources/application.properties
- Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
- Main/build.gradle
- Main/src/main/resources/application.properties
- 화이트 리스트에 Actuator 경로 추가
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Setting : 액추에이터, 프로메테우스 의존성 설정 추가

- Common/src/main/java/com/seveneleven/util/file/Service/FileService.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistDocs.java
- Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistApplication.java
- Main/src/main/java/com/seveneleven/project/service/ProjectChecklistService.java
- Main/src/main/java/com/seveneleven/project/service/ProjectChecklistServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReader.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReaderImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStore.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStoreImpl.java
<br />
체크요청/반려 파일 기능 초안 구현
<br />
1. FileService 수정
2. ProjectChecklistDoc 수정
3. ProjectChecklistController 파일 관련 메서드 추가
4. ProjectCheckRequestService, ProjectCheckRequestServiceImpl 수정
5. CheckRequestFileStore, CheckRequestFileStoreImpl 구현
6. CheckRequestFileReader, CheckRequestFileReaderImpl 구현
<br />
<br />
<br />
> feat: 체크요청/반려 파일 기능 초안

- Admin/src/main/java/com/seveneleven/controller/MemberMgmtController.java
- Common/src/main/java/com/seveneleven/config/TokenProvider.java
- Common/src/main/java/com/seveneleven/config/WebConfig.java
- Main/src/main/java/com/seveneleven/member/controller/MemberController.java
close: #142 
<br />
쿠키 옵션 설정 수정
<br />
1. 쿠키 설정 수정
2. cors 설정 추가
<br />
> Feature/admin member update #142

- Admin/src/main/java/com/seveneleven/controller/AdminMemberDocs.java
- Admin/src/main/java/com/seveneleven/controller/MemberMgmtController.java
- Admin/src/main/java/com/seveneleven/service/MemberMgmtService.java
- Admin/src/main/java/com/seveneleven/service/MemberMgmtServiceImpl.java
- Main/src/main/java/com/seveneleven/member/controller/MemberController.java
<br />
쿠키 설정 변경
<br />
쿠키 httpOnly 설정 변경
<br />
> Feature/cookie setting #148

- Admin/src/main/java/com/seveneleven/controller/AdminAuthController.java
- Admin/src/main/java/com/seveneleven/controller/AdminAuthDocs.java
- Admin/src/main/java/com/seveneleven/controller/AdminMemberController.java
- Admin/src/main/java/com/seveneleven/controller/AdminMemberDocs.java
- Admin/src/main/java/com/seveneleven/dto/GetMemberList.java
- Admin/src/main/java/com/seveneleven/dto/MemberDto.java
- Admin/src/main/java/com/seveneleven/dto/MemberUpdate.java
- Admin/src/main/java/com/seveneleven/service/AdminMemberService.java
- Admin/src/main/java/com/seveneleven/service/AdminMemberServiceImpl.java
<br />
관리자 회원 리팩토링
<br />
1. 관리자 회원 path parameter 수정
2. 회원 목록 조회 검색/페이징 로직 수정
<br />
> Feature/member refactor #146

- Admin/src/main/java/com/seveneleven/controller/AdminMemberController.java
- Main/src/main/java/com/seveneleven/member/controller/MemberController.java
<br />
쿠키 옵션 설정
<br />
1.쿠키 옵션 설정
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Test : 쿠키 옵션 설정

- Common/src/main/java/com/seveneleven/config/WebConfig.java
<br />
의심가는 webconfig 수정
<br />
의심가는 webconfig 수정
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Feat: 마지막 수정(이길..)

- Admin/src/main/resources/application.properties
- Main/src/main/resources/application.properties
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> setting : hikari max life time set 25m

- Admin/src/main/resources/application.properties
- Main/src/main/resources/application.properties
- build.gradle
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Setting/hicari connection set #167

- Admin/src/main/resources/application.properties
- Main/src/main/resources/application.properties
- build.gradle
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Revert 169 setting/hicari connection set #167

- Common/src/main/java/com/seveneleven/config/JwtFilter.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> refactor : add filter request log

- Common/src/main/java/com/seveneleven/config/WebConfig.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> fix : cors add 'www.devlens.work'

- Admin/src/main/java/com/seveneleven/controller/AdminMemberController.java
- Main/src/main/java/com/seveneleven/member/controller/MemberController.java
<br />
쿠키 도메인 설정
<br />
1. 배포 환경에서만 쿠키 도메인이 추가되도록 설정
2. 쿠키 부분 로그 추가
> Feature : 쿠키 도메인 설정

- Common/src/main/java/com/seveneleven/config/AuditorAwareImpl.java
- Common/src/main/java/com/seveneleven/config/TokenProvider.java
- Common/src/main/java/com/seveneleven/util/security/dto/CustomUserDetails.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
- Main/src/main/java/com/seveneleven/board/controller/CommentController.java
- Main/src/main/java/com/seveneleven/board/controller/CommentDocs.java
- Main/src/main/java/com/seveneleven/board/service/CommentService.java
<br />
게시글 및 댓글 AuthenticationPrincipal 추가 및 AutditorAwareImpl 수정
<br />
1. 게시글 및 댓글 AuthenticationPrincipal 추가 
2. AutditorAwareImpl 수정
<br />
1. swagger
> feat: 게시글 및 댓글 AuthenticationPrincipal 추가 및 AutditorAwareImpl 수정

- Common/src/main/java/com/seveneleven/entity/board/Post.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> fix: post entity 수정

- Main/src/main/java/com/seveneleven/project/repository/ProjectRepository.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> fix : logic error

- Admin/src/main/java/com/seveneleven/controller/AdminMemberController.java
- Admin/src/main/java/com/seveneleven/controller/AdminMemberDocs.java
- Admin/src/main/java/com/seveneleven/repository/PasswordHistoryRepository.java
- Admin/src/main/java/com/seveneleven/repository/ProfileHistoryRepository.java
- Admin/src/main/java/com/seveneleven/service/AdminMemberService.java
- Admin/src/main/java/com/seveneleven/service/AdminMemberServiceImpl.java
- Common/src/main/java/com/seveneleven/config/TokenProvider.java
- Common/src/main/java/com/seveneleven/entity/member/MemberProfileHistory.java
- Common/src/main/java/com/seveneleven/util/security/repository/RefreshTokenRepository.java
- Common/src/main/java/com/seveneleven/util/security/service/RefreshTokenServiceImpl.java
- Main/src/main/java/com/seveneleven/member/controller/MemberController.java
- Main/src/main/java/com/seveneleven/member/controller/MemberDocs.java
- Main/src/main/java/com/seveneleven/member/repository/PasswordHistoryRepository.java
- Main/src/main/java/com/seveneleven/member/repository/ProfileHistoryRepository.java
- Main/src/main/java/com/seveneleven/member/service/MemberService.java
- Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
- Main/src/main/java/com/seveneleven/member/service/MyPageServiceImpl.java
<br />
회원 리팩토링 및 이력, 로그 추가
<br />
1. 로그 추가
2. 비밀번호 재설정, 프로필 변경 이력 추가
3. 로그아웃 토큰 로직 수정
<br />
> Feat : 회원 리팩토링 및 이력, 로그 추가

- Common/src/main/java/com/seveneleven/config/SwaggerConfiguration.java
- Common/src/main/java/com/seveneleven/util/file/dto/LinkInput.java
- Common/src/main/java/com/seveneleven/util/file/dto/LinkPayload.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/dto/PostCreateRequest.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
- Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistApplication.java
- Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistReject.java
- Main/src/main/java/com/seveneleven/project/service/ProjectChecklistService.java
- Main/src/main/java/com/seveneleven/project/service/ProjectChecklistServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReaderImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkReader.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkReaderImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStoreImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStore.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStoreImpl.java
<br />
프로젝트 체크리스트 링크 기능 구현 및 파일 기능 수정
<br />
1. 프로젝트 체크리스트 링크 기능 구현
2. 프로젝트 체크리스트 파일 기능 수정
<br />
<br />
<br />
프로젝트 엔티티가 수정되어 DB - creat 필요해보입니다.
바뀐 엔티티 기준 더미데이터 notion 최신화 부탁드립니다.
> Feat : 프로젝트 체크리스트 링크 기능 구현 및 파일 기능 수정

- Admin/src/main/java/com/seveneleven/application/adminProject/AdminProjectFacade.java
- Admin/src/main/java/com/seveneleven/common/BasicStep.java
- Admin/src/main/java/com/seveneleven/repository/AdminProjectStepRepository.java
- Admin/src/main/java/com/seveneleven/service/AdminProjectStepService.java
- Admin/src/main/java/com/seveneleven/service/AdminProjectStepServiceImpl.java
- Admin/src/main/java/com/seveneleven/service/ProjectStepStore.java
- Admin/src/main/java/com/seveneleven/service/ProjectStepStoreImpl.java
<br />
프로젝트 생성 시 기본 단계 추가하도록 변경
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> feat : 프로젝트 생성 시 프로젝트 기본 단계 추가

- Admin/src/main/java/com/seveneleven/member/controller/AdminAuthController.java
- Admin/src/main/java/com/seveneleven/member/controller/AdminAuthDocs.java
- Admin/src/main/java/com/seveneleven/member/dto/MemberDto.java
- Admin/src/main/java/com/seveneleven/member/repository/AdminMemberRepository.java
- Admin/src/main/java/com/seveneleven/member/service/AdminMemberServiceImpl.java
- Common/src/main/java/com/seveneleven/config/JwtFilter.java
- Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
- Common/src/main/java/com/seveneleven/util/security/service/RefreshTokenServiceImpl.java
- Main/src/main/java/com/seveneleven/member/controller/AuthController.java
- Main/src/main/java/com/seveneleven/member/controller/AuthDocs.java
- Main/src/main/java/com/seveneleven/member/controller/MemberDocs.java
- Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
<br />
회원 로직 수정
<br />
1. 활성화 회원만 로그인 되도록 설정
2. 계정 상세 조회에 계정 생성일 추가
3. 토큰 재발급 api 로직 변경
4. 로그 추가
<br />
> Feat: 회원 로직 수정 및 로그 추가

- Common/src/main/java/com/seveneleven/entity/board/Post.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
- Main/src/main/java/com/seveneleven/board/service/CommentService.java
- Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostReader.java
- Main/src/main/java/com/seveneleven/board/service/PostReaderImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostStore.java
- Main/src/main/java/com/seveneleven/board/service/PostStoreImpl.java
<br />
게시글 파트 리팩토링 #134 
<br />
1. PostService 에서 Reader, Store 분리 
<br />
1. 스웨거
> refactor: 게시글 리팩토링

- Main/src/main/java/com/seveneleven/project/controller/MyProjectController.java
- Main/src/main/java/com/seveneleven/project/dto/GetCompanyProject.java
- Main/src/main/java/com/seveneleven/project/service/ProjectService.java
- Main/src/main/java/com/seveneleven/project/service/ProjectServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/dashboard/ProjectReader.java
- Main/src/main/java/com/seveneleven/project/service/dashboard/ProjectReaderImpl.java
<br />
- 내 프로젝트 / 회사 프로젝트 찾기 api 분리
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> feat : 내 프로젝트 / 회사 프로젝트 api 분리

- Admin/src/main/java/com/seveneleven/common/AdminExceptionHandler.java
- Admin/src/main/java/com/seveneleven/company/application/AdminCompanyFacade.java
- Admin/src/main/java/com/seveneleven/company/controller/CompanyController.java
- Admin/src/main/java/com/seveneleven/company/controller/CompanyDocs.java
- Admin/src/main/java/com/seveneleven/company/dto/PostCompany.java
- Admin/src/main/java/com/seveneleven/company/dto/PutCompany.java
- Admin/src/main/java/com/seveneleven/company/repository/AdminCompanyHistoryRepository.java
- Admin/src/main/java/com/seveneleven/company/repository/AdminCompanyHistoryStoreImpl.java
- Admin/src/main/java/com/seveneleven/company/repository/AdminCompanyReaderImpl.java
- Admin/src/main/java/com/seveneleven/company/repository/CompanyRepository.java
- Admin/src/main/java/com/seveneleven/company/service/AdminCompanyHistoryService.java
- Admin/src/main/java/com/seveneleven/company/service/AdminCompanyHistoryServiceImpl.java
- Admin/src/main/java/com/seveneleven/company/service/AdminCompanyHistoryStore.java
- Admin/src/main/java/com/seveneleven/company/service/AdminCompanyService.java
- Admin/src/main/java/com/seveneleven/company/service/AdminCompanyServiceImpl.java
- Admin/src/main/java/com/seveneleven/member/repository/AdminMemberRepository.java
- Admin/src/main/java/com/seveneleven/member/service/AdminMemberService.java
- Admin/src/main/java/com/seveneleven/member/service/AdminMemberServiceImpl.java
- Admin/src/main/java/com/seveneleven/project/controller/AdminProjectController.java
- Admin/src/main/java/com/seveneleven/project/controller/AdminProjectDocs.java
- Admin/src/main/java/com/seveneleven/project/dto/PostProject.java
- Admin/src/main/java/com/seveneleven/project/dto/PutProject.java
- Common/src/main/java/com/seveneleven/entity/member/Company.java
- Common/src/main/java/com/seveneleven/entity/member/CompanyHistory.java
<br />
크로스 테스트 피드백 반영
<br />
ex) 
1. 회사 삭제 시 멤버 삭제
2. 프로젝트 / 회사 validation 추가
3. 회사 이력 테이블 추가 및 이력 저장 기능 추가
<br />
ex)
1. 스웨거 테스트
> Feature/admin fix#185

- Common/src/main/java/com/seveneleven/config/WebConfig.java
<br />
CORS 에 localhost/admin, localhost/main 추가
> Setting: CORS 추가

- Admin/src/main/java/com/seveneleven/AdminApplication.java
- Common/src/main/java/com/seveneleven/config/SwaggerConfiguration.java
- Main/src/main/java/com/seveneleven/MainApplication.java
<br />
ex) 
스웨거 Servers 경로 추가
<br />
- Swagger Servers에 서벼 경로 추가
<br />
> Setting : 스웨거 경로 설정

- Admin/src/main/java/com/seveneleven/company/service/CompanyFileHistoryService.java
- Admin/src/main/java/com/seveneleven/company/service/CompanyFileService.java
- Common/src/main/java/com/seveneleven/entity/file/FileMetadataHistory.java
- Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
- Common/src/main/java/com/seveneleven/util/file/handler/FileHandler.java
- Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataHistoryRepository.java
- Main/src/main/java/com/seveneleven/board/service/PostFileHistoryService.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/java/com/seveneleven/member/service/MemberFileHistoryService.java
- Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileHistoryStore.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileHistoryStoreImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStore.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStoreImpl.java
<br />
도메인별 파일 이력기능 추가
<br />
1. 회사 로고 이미지 등록/삭제 이력 기능 추가
2. 프로필 이미지 등록/삭제 이력 기능 추가
3. 게시물 파일 등록/삭제 이력 기능 추가
4. 체크요청 파일 등록/삭제 이력 기능 추가
5. 체크요청 반려 파일 등록/삭제 이력 기능 추가
6. 관련 service 수정
<br />
1. Swagger 동작 확인
2. S3 버킷 확인
3. DB 데이터 확인
<br />
<br />
> Feat: 파일 이력 등록 추가

- Common/src/main/java/com/seveneleven/entity/project/ProjectAuthorization.java
- Common/src/main/java/com/seveneleven/entity/project/ProjectAuthorizationHistory.java
- Common/src/main/java/com/seveneleven/response/ErrorCode.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationController.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationDocs.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationFacade.java
- Main/src/main/java/com/seveneleven/project/dto/GetMemberAuthorization.java
- Main/src/main/java/com/seveneleven/project/service/ProjectAuthorizationService.java
- Main/src/main/java/com/seveneleven/project/service/ProjectAuthorizationServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationReader.java
- Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationReaderImpl.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Feature/project authorization refactor 2 #191

- Admin/src/main/java/com/seveneleven/AdminApplication.java
- Common/src/main/java/com/seveneleven/config/WebConfig.java
- Main/src/main/java/com/seveneleven/MainApplication.java
> setting: cors 수정

- Common/src/main/java/com/seveneleven/entity/file/LinkHistory.java
- Common/src/main/java/com/seveneleven/util/file/handler/FileHandler.java
- Common/src/main/java/com/seveneleven/util/file/handler/LinkHandler.java
- Common/src/main/java/com/seveneleven/util/file/repository/LinkHistoryRepository.java
- Main/src/main/java/com/seveneleven/board/service/PostLinkHistoryService.java
- Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
- Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkHistoryStore.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkHistoryStoreImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStoreImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStoreImpl.java
<br />
도메인별 링크 이력 기능 추가
<br />
1. 게시물 링크 등록/삭제 이력 추가
2. 체크요청 링크 등록 이력 추가
3. 체크요청 반려 링크 등록 이력 추가
<br />
1. swagger 수행
2. DB 데이터 확인
<br />
<br />
> Feat: 링크 이력 기능

- Common/src/main/java/com/seveneleven/config/JwtAccessDeniedHandler.java
- Common/src/main/java/com/seveneleven/config/JwtAuthenticationEntryPoint.java
<br />
비인증 객체 응답 http status 수정
<br />
> Feat: 비인증 객체 http status 수정

- Admin/src/main/java/com/seveneleven/project/application/AdminProjectFacade.java
- Admin/src/main/java/com/seveneleven/project/dto/PostProject.java
- Admin/src/main/java/com/seveneleven/project/dto/PutProject.java
- Admin/src/main/java/com/seveneleven/project/repository/ProjectTagRepository.java
- Admin/src/main/java/com/seveneleven/project/service/AdminProjectTagService.java
- Admin/src/main/java/com/seveneleven/project/service/AdminProjectTagServiceImpl.java
- Admin/src/main/java/com/seveneleven/project/service/AdminProjectTagStore.java
- Admin/src/main/java/com/seveneleven/project/service/AdminProjectTagStoreImpl.java
- Common/src/main/java/com/seveneleven/config/aop/ControllerAop.java
- Common/src/main/java/com/seveneleven/entity/project/ProjectAuthorization.java
- Common/src/main/java/com/seveneleven/entity/project/ProjectTag.java
- Common/src/main/java/com/seveneleven/entity/project/duplkey/MemberProjectStepId.java
- Common/src/main/java/com/seveneleven/util/CustomDateFormatter.java
- Main/src/main/java/com/seveneleven/company/service/CompanyReader.java
- Main/src/main/java/com/seveneleven/company/service/CompanyReaderImpl.java
- Main/src/main/java/com/seveneleven/company/service/CompanyService.java
- Main/src/main/java/com/seveneleven/company/service/CompanyServiceImpl.java
- Main/src/main/java/com/seveneleven/project/controller/MyControllerFacade.java
- Main/src/main/java/com/seveneleven/project/controller/MyProjectController.java
- Main/src/main/java/com/seveneleven/project/controller/MyProjectDocs.java
- Main/src/main/java/com/seveneleven/project/dto/GetCompanyProject.java
- Main/src/main/java/com/seveneleven/project/dto/GetMyProjectList.java
- Main/src/main/java/com/seveneleven/project/repository/ProjectRepository.java
- Main/src/main/java/com/seveneleven/project/repository/ProjectTagRepository.java
- Main/src/main/java/com/seveneleven/project/service/ProjectService.java
- Main/src/main/java/com/seveneleven/project/service/ProjectServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/project/ProjectReader.java
- Main/src/main/java/com/seveneleven/project/service/project/ProjectReaderImpl.java
- Main/src/main/java/com/seveneleven/project/service/tags/ProjectTagReader.java
- Main/src/main/java/com/seveneleven/project/service/tags/ProjectTagReaderImpl.java
<br />
- 프로젝트 생성, 수정 시 프로젝트 태그 추가하도록 변경
- 프로젝트 읽을 때, 해당 프로젝트의 태그를 읽어오도록 변경
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Feature : project tag 2 #205

- Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시물 생성시 반환값 추가
<br />
게시물 생성시 반환값 추가
<br />
1. swagger 테스트
<br />
<br />
> Update: 게시물 생성시 반환값 추가

- Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
- Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
- Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시물 상세 링크, 파일 반환 추가
<br />
게시물 상세 조회시 게시물 관련 링크, 파일 함께 반환하도록 수정
<br />
1. swagger 테스트
2. 
<br />
<br />
> Update: 게시물 상세 링크, 파일 반환 추가

- Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
Delete Post Link History 파라미터 수정
<br />
PostServiceImpl Delete Post Link History 파라미터 수정
<br />
1.swagger 구동
<br />
<br />
> Fix: Delete Post Link History 파라미터 수정

- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
- Main/src/main/java/com/seveneleven/board/dto/PostListResponse.java
- Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
- Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
- Main/src/main/java/com/seveneleven/board/service/PostReader.java
- Main/src/main/java/com/seveneleven/board/service/PostReaderImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
- Main/src/main/java/com/seveneleven/project/repository/ProjectStepRepository.java
<br />
게시판의 전체 게시물 목록 조회 기능 수정
<br />
1. 프로젝트 내 모든 단계의 총 게시물 조회 기능 추가
2. 게시글 목록 조회 시 댓글 수 컬럼 추가
<br />
1. 스웨거
> feat: 전체 게시물 조회 기능 추가

- Admin/src/main/java/com/seveneleven/project/service/AdminProjectTagServiceImpl.java
- Admin/src/main/java/com/seveneleven/project/service/AdminProjectTagStoreImpl.java
<br />
ex) 
<br />
프로젝트 생성 시 태그가 없을 때 생성이 불가능해지며 발생하던 문제 해결
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> refactor : project tag nullable

- Common/src/main/java/com/seveneleven/entity/file/constant/FileCategory.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/dto/PostCreateRequest.java
- Main/src/main/java/com/seveneleven/board/dto/PostUpdateRequest.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시물 파일/링크 업데이트 로직 변경
<br />
게시물 파일/링크 업데이트 로직 변경
<br />
1. swagger작동
2. s3 버킷확인
3. db 확인
<br />
<br />
> Update: 게시물 파일/링크 업데이트 로직 변경

- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
- Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
- Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
- Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
- Main/src/main/java/com/seveneleven/board/service/CommentReader.java
- Main/src/main/java/com/seveneleven/board/service/CommentReaderImpl.java
- Main/src/main/java/com/seveneleven/board/service/CommentService.java
- Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시글 및 댓글 기능에 작성자 여부 컬럼 추가
<br />
1. 게시글 및 댓글 기능에 작성자 여부 컬럼 추가
2. 
<br />
1. swagger
> Feature : 게시글 및 댓글 작성자 확인 기능 수정

- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/dto/PostUpdateRequest.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
파일/링크 수정 롤백
<br />
파일/링크 수정 롤백
<br />
<br />
<br />
> Chore: 파일/링크 수정 롤백

- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시글 권한(작성자, 관리자) 수정
<br />
1. 게시글 수정 및 삭제 시 권한(작성자+관리자) 체크 메서드 수정
<br />
1. 스웨거
> feat: 게시글 권한(작성자, 관리자) 수정

- Admin/src/main/java/com/seveneleven/company/application/AdminCompanyFacade.java
- Admin/src/main/java/com/seveneleven/company/controller/CompanyController.java
- Admin/src/main/java/com/seveneleven/company/controller/CompanyDocs.java
- Admin/src/main/java/com/seveneleven/company/dto/PutCompany.java
- Admin/src/main/java/com/seveneleven/company/service/AdminCompanyService.java
- Admin/src/main/java/com/seveneleven/company/service/AdminCompanyServiceImpl.java
- Common/src/main/java/com/seveneleven/entity/member/Company.java
<br />
회사 삭제 수정 병합
<br />
스웨거 테스트
<br />
> feat : 회사 수정 회사 상태 변경 추가 # 257

- Common/src/main/java/com/seveneleven/util/file/dto/FileMetadataResponse.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
<br />
modify file upload return value
<br />
modify file upload return value
<br />
<br />
<br />
> chore: modify file upload return value

- Common/src/main/java/com/seveneleven/util/file/dto/LinkResponse.java
- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
- Main/src/main/java/com/seveneleven/board/service/PostLinkServiceImpl.java
<br />
ex) 
modify link upload return
<br />
modify link upload return
<br />
<br />
<br />
> Chore: modify link upload return

- Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
- Common/src/main/java/com/seveneleven/entity/project/Project.java
- Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
- Main/src/main/java/com/seveneleven/member/controller/MemberController.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationController.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistDocs.java
- Main/src/main/java/com/seveneleven/project/dto/GetChecklistApplication.java
- Main/src/main/java/com/seveneleven/project/dto/GetProjectDetail.java
- Main/src/main/java/com/seveneleven/project/dto/GetProjectStep.java
- Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistApplication.java
- Main/src/main/java/com/seveneleven/project/repository/ProjectStepRepository.java
- Main/src/main/java/com/seveneleven/project/service/ProjectCheckRequestServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/ProjectServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/ProjectStepServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/step/StepReader.java
- Main/src/main/java/com/seveneleven/project/service/step/StepReaderImpl.java
- Main/src/main/java/com/seveneleven/util/methodauthorize/ProjectAuthorizationCheckServiceImpl.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> refactor : project detail refactor

- Common/src/main/java/com/seveneleven/entity/board/Post.java
- Common/src/main/java/com/seveneleven/entity/board/constant/PostFilter.java
- Main/src/main/java/com/seveneleven/board/dto/PostListResponse.java
- Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
- Main/src/main/java/com/seveneleven/board/dto/RelatedPostResponse.java
- Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
- Main/src/main/java/com/seveneleven/board/service/PostReader.java
- Main/src/main/java/com/seveneleven/board/service/PostReaderImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시글 상세 조회시 원글 및 답글 필드 추가
#268 
<br />
1. 게시글 상세 조회시 원글 및 답글 id, title 추가
<br />
1. 스웨거
> feat: 게시글 상세 조회시 원글 및 답글 필드 추가

- Common/src/main/java/com/seveneleven/entity/board/Post.java
<br />
게시글 상세 조회 시 원글 및 답글 구분 에러 수정
<br />
1. Post Entity의 isParent() 메서드 수정
<br />
1. 스웨거
> fix: 게시글 상세 조회 시 원글 및 답글 구분 에러 수정

- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시글 상세 조회 api 로직 수정 후 반영 안 되는 이슈로 로그 추가
<br />
1. 게시글 상세 조회 api 로직 수정 후 반영 안 되는 이슈로 로그 추가
> fix: 게시글 상세 조회 api에 log 추가

- Common/src/main/java/com/seveneleven/entity/board/Post.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시글 상세 조회 시 500 에러 해결
<br />
1. isParent() 메서드 수정하여 해결
<br />
1. 스웨거
> fix: 게시글 상세 조회 시 500 에러 해결

- Common/src/main/java/com/seveneleven/entity/project/Checklist.java
- Common/src/main/java/com/seveneleven/entity/project/ChecklistHistory.java
- Common/src/main/java/com/seveneleven/entity/project/Project.java
- Common/src/main/java/com/seveneleven/entity/project/constant/ChecklistStatus.java
- Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
- Main/src/main/java/com/seveneleven/project/dto/DeleteProjectChecklist.java
- Main/src/main/java/com/seveneleven/project/dto/GetProjectStep.java
- Main/src/main/java/com/seveneleven/project/dto/GetStepChecklist.java
- Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklist.java
- Main/src/main/java/com/seveneleven/project/dto/PutProjectChecklist.java
- Main/src/main/java/com/seveneleven/project/repository/ChecklistRepository.java
- Main/src/main/java/com/seveneleven/project/service/ProjectServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/ProjectStepServiceImpl.java
- Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistReaderImpl.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> Refactor/checklist status #270

- Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistApplication.java
- Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStoreImpl.java
<br />
ex) 
<br />
- 프론트 요청으로 체크리스트 승인 요청 시 링크 삭제
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> fix : application link delete

- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/service/PostFileService.java
- Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
- Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
<br />
프로필 사진, 게시물 파일 권한 추가
<br />
1. 프로필 사진 업로드/삭제 권한 추가
2. 게시물 파일 업로드/삭제 권한 추가
<br />
1. swagger 구동
2. DB 확인
3. S3 버킷 확인
<br />
<br />
> Feat: 프로필 사진, 게시물 파일 권한 추가

- Main/src/main/java/com/seveneleven/board/controller/BoardController.java
- Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
- Main/src/main/java/com/seveneleven/board/service/PostLinkServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostService.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
<br />
게시물 링크 api 권한 추가
<br />
1. 게시물 링크 api 권한 추가
<br />
1. swagger구동
2. db 확인
<br />
<br />
> Feat: 게시물 링크 api 권한 추가

- Admin/src/main/java/com/seveneleven/project/dto/GetProject.java
<br />
- 관리자 프로젝트 상세에 회사 id 전송하도록 변경
<br />
ex)
- corsheaders
- jwt
<br />
> refactor : detail project company id add

- Admin/src/main/java/com/seveneleven/project/service/AdminProjectServiceImpl.java
<br />
ex) 
<br />
ex) 
<br />
ex)
<br />
ex)
- corsheaders
- jwt
<br />
> refactor : 프로젝트 목록 조회 시 빈 데이터가 없을 때 예외 던지지 않도록 변경

- Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataRepository.java
- Main/src/main/java/com/seveneleven/board/dto/GetCommentDetailResponse.java
- Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
- Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
- Main/src/main/java/com/seveneleven/board/service/CommentService.java
- Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
- Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
- Main/src/main/java/com/seveneleven/member/service/MemberService.java
- Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
<br />
게시물, 댓글 작성자 프로필 이미지 추가
<br />
1. PostService, PostServiceImpl 수정
2. CommentService, CommentServiceImple 수정
3. 관련 DTO 수정
4. FileMetadataRepository 수정
5. MemberService 수정
<br />
1. swagger 구동
2. DB확인
<br />
<br />
> Feat: 게시물, 댓글 작성자 프로필 이미지 추가

- Common/src/main/java/com/seveneleven/entity/project/constant/MemberType.java
- Main/src/main/java/com/seveneleven/project/dto/GetMemberAuthorization.java
- Main/src/main/java/com/seveneleven/project/service/ProjectAuthorizationServiceImpl.java
<br />
- Member Authorization Admin 제대로 반환하도록 변경
<br />
ex)
- corsheaders
- jwt
<br />
> refactor : authorization add admin

- Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
- Main/src/main/java/com/seveneleven/board/service/CommentReader.java
- Main/src/main/java/com/seveneleven/board/service/CommentReaderImpl.java
- Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
- Main/src/main/java/com/seveneleven/notification/controller/NotificationController.java
- Main/src/main/java/com/seveneleven/notification/service/NotificationService.java
<br />
#292 
SSE를 사용하여 댓글 알림 기능 구현
<br />
1. 댓글 등록 시 작성자에게 알림 전송 기능 구현
2. Notification Controller & Service 작성
<br />
1. postman
3. test server
> Feature: notification comment #292

- Admin/src/main/java/com/seveneleven/member/repository/AdminMemberRepository.java
- Admin/src/main/java/com/seveneleven/member/service/InactiveUserCleanupService.java
- Admin/src/main/resources/application.properties
- Common/src/main/java/com/seveneleven/config/SchedulerConfig.java
<br />
오래된 비활성화 회원 삭제 스케줄링 기능
<br />
1주일 이상 비활성화 상태인 회원 삭제
<br />
> Feat: 스케줄링 기능

- Common/src/main/java/com/seveneleven/entity/project/Checklist.java
<br />
- 체크리스트 승인 요청 반려 시 체크리스트 상태가 반려 상태로 변경
- 스웨거 테스트
> fix : add admin main facade transactional
